### PR TITLE
cp rephrase whole kernel to mrkernel

### PR DESCRIPTION
**Pull request by maxregnerklos**
cp rephrase whole kernel to mrkernel

### CODE REVIEW

**Comment by maxregnerklos** [comment]
cp rephrase whole kernel to mrkernel

**Review by maxregnerklos — COMMENTED** [review]
cp rephrase whole for android 14

**Comment by maxregnerklos** [comment]
cp rephrase

**Comment by rushiranpise** [comment]
What is this about?

**Pull request closed without merging**
